### ISSUE TITLE
Map won't show in survey/Qualtrics

### ISSUE THREAD

**Issue by twuerzer** [keita-makino/qualtrics-map#154]
hi there.
So.... did the step by step setup.
Map and the two form fields show (w my lat long) in the Look&Feel and in the question preview.
They don't show in the survey preview or in published survey.  Only the question text shows -- no form fields, no map.
I tried Chrome, Edge, Firefox.

The console actually shows an error:  "SE API Error:  ReferenceError: mapRender is not defined"
Again, the question preview works.... just not the survey preview or published version.

Any ideas?

**Comment by keita-makino** [comment]
HI @twuerzer,

It says the question failed to load the `mapRender` function but it looks weird that it happens only in the production environment.
You can invite me to your survey project as a collaborator so I can investigate.

**Comment by twuerzer** [comment]
security measures of my university won't allow for that.

We could find a short zoom session and screen share, if you would like that
effort?
If you don't mind that.  You would receive an email invite from
***@***.*** if you let me know your zoom email

**Comment by keita-makino** [comment]
I can join a Zoom call but it might also work if you create a _mock_ survey project that contains only one question with the map component and share it with me.

**Comment by keita-makino** [comment]
Closing as the issue has been identified over the communication and now (seems to be) fixed by 2.0.2.

**Comment by maying0120** [comment]
hi, 
@keita-makino and @twuerzer 
Could you please tell me what errors you meet, basically I also follow the instruction and cannot see the map on the preview page?
 I suggest the author can record the video to demo it, which will be more clear.

Thanks,
Ying Ma
