### ISSUE TITLE
Map Not Loading/Qualtrics Changed

### ISSUE THREAD

**Issue by ankmb1979** [keita-makino/qualtrics-map#183]
Hello, 

Qualtrics has changed its item options, so "Text + Form" is not available (only Text, Text/Graphic, Form). It seems to only work when using Form, deleting the theme from look/feel (if any), and using classic, modern, or flat (under look and feel, layout). It might be helpful to update your instructors for other folks. 
Thank you!

**Comment by keita-makino** [comment]
Thank you for reporting it, I have changed the readme.
