### ISSUE TITLE
Fix the starting point of the map.

### ISSUE THREAD

**Issue by sharmaishant92** [keita-makino/qualtrics-map#42]
Hi @keita-makino 
I cannot thank you enough for providing the scripts.
I just have a small query. Since I  have no prior knowledge of Java and HTML, I am finding it hard to fix the starting point of the map. Right now, it starts from UC Davis but I want it to start from Tennessee. 
I have no clue which code to edit to achieve this and need assistance from you. Please guide me on the appropriate file or script to look for to do this.

**Comment by keita-makino** [comment]
Hi @sharmaishant92,

Thank you for your inquiry.

As you mentioned, I have coded the app to set the default location as Davis, CA. But it will be ignored if you enable using the user location provided by Qualtrics, attaching the code shown under “Header Settings” section in the readme.
Did you do this process and still got Davis as the default location?

**Comment by sharmaishant92** [comment]
Hi @keita-makino 

I followed all the steps in the read me section including header settings. Still I am getting UC Davis as the starting point. Please assist me with a code or documentation to revise the script to make Tennessee or any other location as an initial point.  

Thanks

**Comment by keita-makino** [comment]
@sharmaishant92 Could you attach screenshots showing the header code section?

I will also check where you should change to make Tennessee as the default point.

**Comment by sharmaishant92** [comment]
@keita-makino Here is the dropbox link to the screenshot of the header:
https://www.dropbox.com/s/byaoicwi87g1e50/Screenshot%202020-04-25%2021.57.54.png?dl=0

**Comment by keita-makino** [comment]
@sharmaishant92
What the 38 means?

**Comment by sharmaishant92** [comment]
@keita-makino I replaced the country code with 38 to check if the initial position changes but no luck. I have reverted it back to '${loc://CountryCode}') but still the initial position is UC Davis.

**Comment by keita-makino** [comment]
@sharmaishant92 

Did you check the question in per-question-preview mode or preview for the entire survey? The preview for each question does not capture the geolocation of the user so that the country and zipcode setting will be ignored.

If you need to change the default location, please follow the steps below.

1. Open "bundle.js" with some text editor (e.g., vscode).
2. Search `{center:{lat:38.542096,lng:-121.771202},zoom:6}` that defines the default location.
3. Change the lat, lng and zoom (optional) to your preferred default location. Please refer to [this](https://stackoverflow.com/questions/9356724/google-map-api-zoom-range) for how the zoom level works.
4. Re-upload the bundle.js and follow the steps in the readme.

**Comment by sharmaishant92** [comment]
@keita-makino Thanks for sharing the steps. 

I checked the map both in the survey preview and question preview mode. I even checked it using the anonymous survey link but in every case, the initial point is UC Davis. 
I did try what you suggested but after doing this, the entire map interface disappeared from the survey ([screenshot](https://www.dropbox.com/s/sdxuvjs6v8azdl3/Screenshot%202020-04-27%2021.17.07.png?dl=0)). 
I have attached the revised Bundle.js. ([bundle.js.zip](https://github.com/keita-makino/qualtrics-map/files/4543033/bundle.js.zip))
Previously center command was referring to a function but I changed it to the statement you provided. 
Please assist me further. I appreciate your efforts in taking the time to resolve this. 
Thanks
Ishant

**Comment by seed-of-apricot** [comment]
@sharmaishant92 

No you have to change only the numbers, don't change anything than that.
```
{center:{lat:000.0000,lng:000.0000},zoom:0}
```

**Comment by keita-makino** [comment]
@sharmaishant92 

No you have to change only the numbers, don't change anything than that.
```
{center:{lat:000.0000,lng:000.0000},zoom:0}
```

(I by mistake once made the same comment from my personal account)

**Comment by sharmaishant92** [comment]
@keita-makino I did the same I changed the underlined part in the bundle.js but no luck: 
Before:
Do={center:function(e,t){e.setCenter(t)},draggable:function(e,t){e.setDraggable(t)},
After:
Do={center:{lat:35.860119,lng:-86.660156},{e.setCenter(t)},draggable:function(e,t){e.setDraggable(t)},

This made map disappear.

**Comment by seed-of-apricot** [comment]
@sharmaishant92 

You would change the lat and lng only, don't change the function. You're referring to a different location.  
When you open and search the string listed in step 2, you will find only one exact match.

![image](https://user-images.githubusercontent.com/26666870/80441738-5cc90e00-88c0-11ea-87b5-149ab2e8931c.png)

**Comment by keita-makino** [comment]
@sharmaishant92 

You would change the lat and lng only, don't change the function. You're referring to a different location.  
When you open and search the string listed in step 2, you will find only one exact match.

![image](https://user-images.githubusercontent.com/26666870/80441738-5cc90e00-88c0-11ea-87b5-149ab2e8931c.png)

**Comment by sharmaishant92** [comment]
@keita-makino 
I think I am using a different bundle.js file as I am not able to find the section you are referring to ([screenshot](https://www.dropbox.com/s/nefp4w24ejn7hnk/Screenshot%202020-04-27%2021.57.45.png?dl=0)).
I am downloading this file from the latest release page [(Link)](https://github.com/keita-makino/qualtrics-map/releases/tag/1.0.0).
If possible, please share your version of bundle file.

**Comment by keita-makino** [comment]
@sharmaishant92 
I've found out the cause and potential fix.
You're right, I was referring to a source code of an older version so I built a new distribution in the current environment (I guess the latest version was once built with my work computer. Now we need to stay home).

Consequently, the fix should be:

1. Open "bundle.js" with some text editor (e.g., vscode).
2. Search **`{lat:37.542096,lng:-121.771202}`** that defines the default location.
3. Change the value of lat and lng to your preferred default location.
4. (Optional) Search **`{zoom:14}`** that defines the default zoom.
5. (Optional) Change the value of zoom to your preferred default scaling. Please refer to [this](https://stackoverflow.com/questions/9356724/google-map-api-zoom-range) for how the zoom level works.
6. Re-upload the bundle.js and follow the steps in the readme.

**Comment by sharmaishant92** [comment]
Thanks @keita-makino 

This fix worked. here is the [screenshot](https://www.dropbox.com/s/xefb3rxj9kfopmb/Screenshot%202020-05-07%2013.12.16.png?dl=0)
Thanks for all your help.
