### ISSUE TITLE
Location data

### ISSUE THREAD

**Issue by pi31415314** [keita-makino/qualtrics-map#45]
I've trying to capture the location when someone enters there location using the address box and/or dropping the pin. Right now if they drop a pin the data gets collected however if they type in an address it doesn't work.  Also the map that is displayed is zoomed in too far - is there a way to change this as well as where the map is centered to? Please could you help point me in the right direction.

**Comment by keita-makino** [comment]
Hello @pi31415314, sorry that I didn't respond you for long.

As far as I know the map works in both address -> pin to pin -> address direction.
If you still see the issue and like to resolve it, could you upload some images to show what's happening?

**Comment by keita-makino** [comment]
Closed with inactivity.
