### ISSUE TITLE
get lat lon instead of address

### ISSUE THREAD

**Issue by KayCritchell** [keita-makino/qualtrics-map#63]
Hello,
first, thank you for this, it's very handy!
I am not a java programmer, so I'm struggling to make a couple of modifications.
I am trying to get participants to select locations that are in the ocean, I would like to get the lat and lon from the map instead of an address. How should I modify the script?
Also, how can I change the default starting location?
Thanks again,
K

**Comment by keita-makino** [comment]
@KayCritchell Thank you for your inquiry.

First, the component retrieves the lat/lng of the dropped pins in the map so the record that you will see in the exported dataset is something like this: `{"lat":38.50848634115649,"lng":-138.04154760849607}`. When the user clicks a location that cannot be geocoded, nothing will be auto-filled in the form entry so please just add some note in the description.

About the default location, it detects the geolocation of the survey participant and set as the default. This does not use the GPS feature of the browser and instead rely on metadata given by Qualtrics so I am not sure if this is 100% working in all the locations in the world. At least in my area it works though. How does it work right now?

To change the default location you will need to edit the source and build the component by yourself so if the current schema does not work please let me know, I will deal with it then.

**Comment by RamonZavala** [comment]
Hello Keita, 

I've followed your instructions for map solution and it works quite well except for the default location. You mentioned that the default location is based on Qualtrics metadata, but it's starting me out in the mountainous wilderness east of the SF Bay area. I need it a bit to the north. Short of building the component by myself (I don't code), is there a way to get it to default to a specific lat/long? Even a ZIP code?

Thanks for any help you can provide!

**Comment by seed-of-apricot** [comment]
Hi @RamonZavala, thank you for the inquiry.
Could you show the screenshot of the initial location (if there's nothing in the default zoom level please zoom out) and/or share the survey on Qualtrics with me?

**Comment by keita-makino** [comment]
Hi @RamonZavala, thank you for the inquiry.
Could you show the screenshot of the initial location (if there's nothing in the default zoom level please zoom out) and/or share the survey on Qualtrics with me?

**Comment by RamonZavala** [comment]
Thanks for the response. Here's a screenshot of the map zoomed out 3x. https://imgur.com/a/N3E1SHY

Also, I think I know your name. We may work at the same institution. Look me up in the directory. 

Thanks again for your help!

**Comment by shswinea** [comment]
Hi Keita,

What an amazing resource this is!  I'm planning to incorporate your code into a survey I'm doing for my dissertation.  I've been able to follow your steps successfully to use the mapping tool in a Qualtrics survey item, but I'm having a similar problem to @RamonZavala where my initial location is being shown as being in California.  Is this something you were able to resolve together?  I'd appreciate any input and thanks again for making this component publicly available.

**Comment by keita-makino** [comment]
Hi @shswinea,

I found that it may not work if you have a URL restriction of the Google Maps JavaScript API. I'll be investigating the issue and release a new version if it can be addressed on our end.

**Comment by shswinea** [comment]
Hi Keita,

Thank you for your response!  At the time that I was using your code, my API key did not have any application or API restrictions.  If these are the restrictions you're talking about, that may not be the issue, at least on my end.  Despite this small issue your code works wonderfully and I'm grateful to have access to it.  I'll be looking out for updates from you and thanks again.

-Savannah

**Comment by keita-makino** [comment]
@RamonZavala, @shswinea I have released 1.2.0 that would fix your issue. Please see [the release page](https://github.com/keita-makino/qualtrics-map/releases/tag/1.2.0), try it and let me know if it's resolved.

**Comment by shswinea** [comment]
Hi Keita, thank you for working on this!  I see the new mapRender function, and I inputted a lat and long for where I want my map to start out.  However, when I preview the Qualtrics block, it still starts me out in California, but in a different location this time.  I've attached a picture for your reference.  I'm not sure if @RamonZavala is having the same issue as me. Thanks again for your hard work! -Savannah
![Qualtrics Mapping Image](https://user-images.githubusercontent.com/81324547/112700436-8a1d9380-8e64-11eb-8dda-080ba30e52cd.JPG)

**Comment by keita-makino** [comment]
@shswinea Could you show me what you've written in the JavaScript editor?

**Comment by shswinea** [comment]
Sure!  I think this is what you're referencing?  Let me know if you also want to see what I have in the header section of the survey!
![Qualtrics Mapping JavaScript Editor](https://user-images.githubusercontent.com/81324547/112701397-dff33b00-8e66-11eb-923f-fb21aaddf8ae.JPG)

**Comment by keita-makino** [comment]
@shswinea OK so you need to use only the latter one so please remove the first `Qualtrics.SurveyEngine.addOnReady...`.

**Comment by shswinea** [comment]
Oh wow!  Sorry, I see my mistake.  It's working perfectly!  Thank you so much!

**Comment by keita-makino** [comment]
Closing as the issue has been solved.
