### ISSUE TITLE
can't get location when dragging the pin

### ISSUE THREAD

**Issue by wudunxu** [keita-makino/qualtrics-map#67]
I can't automatically get the location when dragging the pin on the map.

**Comment by keita-makino** [comment]
Hi @wudunxu, could you please give me which kind of error you get?
You can open the browser's inspector (e.g., `Ctrl+Shift+I` in Chrome on Windows) and visit `console` tab to see the error.

One cause might be because you didn't enable Google APIs, possibly?

**Comment by wudunxu** [comment]
> Hi @wudunxu, could you please give me which kind of error you get?
> You can open the browser's inspector (e.g., `Ctrl+Shift+I` in Chrome on Windows) and visit `console` tab to see the error.
> 
> One cause might be because you didn't enable Google APIs, possibly?

Hi, @keita-makino , I have made a test link here: https://hku.au1.qualtrics.com/jfe/form/SV_bJzU5QfpbWuc0qF
The chrome report that `This site overrides Array.from() with an implementation that doesn't support iterables, which could cause Google Maps JavaScript API v3 to not work correctly.` In the meantime, once I submit answers via my link, the qualtrics received blank info on the address. I really feel confused. I look forward to your reply. Thanks a lot.

**Comment by keita-makino** [comment]
Hi @wudunxu,
Indeed, I have taken the sample survey and it worked correctly. Didn't you get my response that locates in Davis, CA?

**Comment by wudunxu** [comment]
Dear Keita,
Thanks for your reply. I have double-checked the "Data and Analysis" page and I didn't receive your response. I think there should exist some bugs in uploading.

**Comment by keita-makino** [comment]
@wudunxu Sorry for late response and thank you for your update.
Could you possibly invite me as a collaborator of the survey so I can investigate?
I think what you shared was a demo survey so there should be no sensitive information.

**Comment by wudunxu** [comment]
Dear Keita,

Thank you for your reply

May I have your email address in Qualtrics so that I can add you as a
collaborator?

Best regards,
Dunxu


Keita Makino <notifications@github.com> 于2020年12月22日周二 上午5:11写道：

**Comment by keita-makino** [comment]
You can use kemakino@ucdavis.edu to invite me.

**Comment by keita-makino** [comment]
@wudunxu I previewed the survey and the response seems to be successfully collected. Do you check the data by downloading csv, sav or something else?

**Comment by wudunxu** [comment]
Dear Keita,

Thank you for your reply. I have checked the download csv file and noted that it was fine.

And I also noted that the collected data can only be viewed in download files and couldn't be displayed in the dashboard.

Thanks again.

**Comment by seed-of-apricot** [comment]
Sounds good :) hope your project goes well with the map.

**Comment by keita-makino** [comment]
Sounds good :) hope your project goes well with the map.
