### ISSUE TITLE
How to force validation on a map question without requiring marker to be dropped?

### ISSUE THREAD

**Issue by crtez** [keita-makino/qualtrics-map#93]
I have a question that asks for a respondent's address.

Currently, the question allows the respondent to drop a pin and not fill in an address, but if they fill in an address and don't drop a pin, it fails validation.

![image](https://user-images.githubusercontent.com/27513125/112931786-62d3fa00-90e2-11eb-9db6-e5dcbe0c1b31.png)

**Comment by keita-makino** [comment]
This is an intended behavior. The component collects lat and lng in the json format. If the behavior you have referred to is allowed, there will be a mix of address string and the json response, in which some might be un-geocodable string (i.e., not a valid address).

**Comment by crtez** [comment]
Thanks for the response--is there any way to separate the Google address lookup bar and the map component? I ran some test responses and it seems like the only answer recorded is the lat/long of the pin dropped on the map.

For example, if someone put this in the address lookup bar:
1600 Pennsylvania Avenue NW, Washington, D.C.

but dropped a pin on Chicago, this is what it looks like in the Qualtrics data:

![image](https://user-images.githubusercontent.com/27513125/113246342-7c11ad80-927e-11eb-8127-72f1170002f5.png)

**Comment by keita-makino** [comment]
The textbox is meant to search an address over Google Maps JavaScript API and if you click one of the suggestions the map will place the pin.

I'm not sure in which situation we'd need two different addresses shown in the textbox and in the map, but how about adding one question with a textbox before the map question?

**Comment by crtez** [comment]
Ah! I see where my confusion stems from then--a pin isn't being dropped on the map when I click a suggestion. Is there any reason that it's failing to do so? I've tried it two ways, one with a map center specified and one without. Thanks again for your continued support!

**Comment by keita-makino** [comment]
Could you check what error do you get with the map?
You can get it by pressing Ctrl + Shift + I in your browser when you see the map component and then click Console tab.

**Comment by crtez** [comment]
Ah, maybe it's a problem with my API key.
![image](https://user-images.githubusercontent.com/27513125/113505683-0f104900-9506-11eb-84d7-0ceafbbc91af.png)

**Comment by keita-makino** [comment]
@crtez Thank you, what would you see when you turn on Maps JavaScript API in the GCP settings?

I might need to update the readme if this is needed.

**Comment by crtez** [comment]
Fixed the problem! The key had access to the Maps JavaScript API and the Places API but not the Geocoding API. I think I might've seen an older version of the README when I was first using the package. Thanks for all your support!

**Comment by keita-makino** [comment]
Yeah sorry that I hadn't updated the docs when published 1.2.0, but am glad to hear that you resolved the issue.
